In [1]:
import os
os.getcwd()
os.chdir("C:/Users/L-ven Lew/Desktop/UM/Semester 4 UM/WQD 7005 Data Mining/Final Exam/Final Exam Question 1")
os.getcwd()

'C:\\Users\\L-ven Lew\\Desktop\\UM\\Semester 4 UM\\WQD 7005 Data Mining\\Final Exam\\Final Exam Question 1'

In [2]:
import requests
import bs4
import json
import datetime
import pandas as pd
page = requests.get("https://finance.yahoo.com/quote/MBBM.KL/history?period1=1425945600&period2=1583798400&interval=1d&filter=history&frequency=1d")

from bs4 import BeautifulSoup
soup = BeautifulSoup(page.content, 'html.parser')
#print(soup.prettify())

listScript = soup.find_all("script")
for script in listScript:
    txtScript = script.string
    if type(txtScript) is bs4.element.NavigableString and txtScript.find('HistoricalPriceStore') != -1:
        MBB = pd.DataFrame(columns=['date','close'])
        txtInfo = txtScript[txtScript.find('HistoricalPriceStore'):txtScript.find('}],"isPending":false,"firstTradeDate":')]
        txtInfo = "{\"" + txtInfo + "}]}}"
        objJson = json.loads(txtInfo)
        for price in objJson['HistoricalPriceStore']['prices']:
            txtDate = ""
            txtClose = ""
            for attr,val in price.items():
                if attr == "date" and val != None:
                    txtDate = datetime.datetime.fromtimestamp(val).strftime('%Y-%m-%d')
                if attr == "close" and val != None:
                    txtClose = str(val)
            if txtDate != "" and txtClose != "":
                MBB = MBB.append({"date":txtDate, "close":txtClose}, ignore_index=True)
        print(MBB)
        
MBB.to_csv(r"C:/Users/L-ven Lew/Desktop/UM/Semester 4 UM/WQD 7005 Data Mining/Final Exam/Final Exam Question 1/MBB.csv",index = False)

            date              close
0     2020-03-09  8.239999771118164
1     2020-03-06                8.5
2     2020-03-05  8.529999732971191
3     2020-03-04  8.470000267028809
4     2020-03-03   8.40999984741211
...          ...                ...
1237  2015-03-16   9.09000015258789
1238  2015-03-13  9.100000381469727
1239  2015-03-12  9.119999885559082
1240  2015-03-11   9.09000015258789
1241  2015-03-10  9.229999542236328

[1242 rows x 2 columns]

In [3]:
import requests
import bs4
import json
import datetime
import pandas as pd
page = requests.get("https://finance.yahoo.com/quote/COMM.KL/history?period1=1425945600&period2=1583798400&interval=1d&filter=history&frequency=1d")

from bs4 import BeautifulSoup
soup = BeautifulSoup(page.content, 'html.parser')
#print(soup.prettify())


listScript = soup.find_all("script")
for script in listScript:
    txtScript = script.string
    if type(txtScript) is bs4.element.NavigableString and txtScript.find('HistoricalPriceStore') != -1:
        CIMB = pd.DataFrame(columns=['date','close'])
        txtInfo = txtScript[txtScript.find('HistoricalPriceStore'):txtScript.find('}],"isPending":false,"firstTradeDate":')]
        txtInfo = "{\"" + txtInfo + "}]}}"
        objJson = json.loads(txtInfo)
        for price in objJson['HistoricalPriceStore']['prices']:
            txtDate = ""
            txtClose = ""
            for attr,val in price.items():
                if attr == "date" and val != None:
                    txtDate = datetime.datetime.fromtimestamp(val).strftime('%Y-%m-%d')
                if attr == "close" and val != None:
                    txtClose = str(val)
            if txtDate != "" and txtClose != "":
                CIMB = CIMB.append({"date":txtDate, "close":txtClose}, ignore_index=True)
        print(CIMB)
        
CIMB.to_csv(r"C:/Users/L-ven Lew/Desktop/UM/Semester 4 UM/WQD 7005 Data Mining/Final Exam/Final Exam Question 1/CIMB.csv",index = False)

            date              close
0     2020-03-09  4.199999809265137
1     2020-03-06  4.440000057220459
2     2020-03-05                4.5
3     2020-03-04  4.539999961853027
4     2020-03-03                4.5
...          ...                ...
1238  2015-03-16  5.909999847412109
1239  2015-03-13  5.920000076293945
1240  2015-03-12  5.849999904632568
1241  2015-03-11  5.800000190734863
1242  2015-03-10  5.949999809265137

[1243 rows x 2 columns]

In [4]:
import requests
import bs4
import json
import datetime
import pandas as pd
page = requests.get("https://finance.yahoo.com/quote/RHBC.KL/history?period1=1425945600&period2=1583798400&interval=1d&filter=history&frequency=1d")

from bs4 import BeautifulSoup
soup = BeautifulSoup(page.content, 'html.parser')
#print(soup.prettify())


listScript = soup.find_all("script")
for script in listScript:
    txtScript = script.string
    if type(txtScript) is bs4.element.NavigableString and txtScript.find('HistoricalPriceStore') != -1:
        RHB = pd.DataFrame(columns=['date','close'])
        txtInfo = txtScript[txtScript.find('HistoricalPriceStore'):txtScript.find('}],"isPending":false,"firstTradeDate":')]
        txtInfo = "{\"" + txtInfo + "}]}}"
        objJson = json.loads(txtInfo)
        for price in objJson['HistoricalPriceStore']['prices']:
            txtDate = ""
            txtClose = ""
            for attr,val in price.items():
                if attr == "date" and val != None:
                    txtDate = datetime.datetime.fromtimestamp(val).strftime('%Y-%m-%d')
                if attr == "close" and val != None:
                    txtClose = str(val)
            if txtDate != "" and txtClose != "":
                RHB = RHB.append({"date":txtDate, "close":txtClose}, ignore_index=True)
        print(RHB)
        
RHB.to_csv(r"C:/Users/L-ven Lew/Desktop/UM/Semester 4 UM/WQD 7005 Data Mining/Final Exam/Final Exam Question 1/RHB.csv",index = False)

            date              close
0     2020-03-09   5.46999979019165
1     2020-03-06  5.699999809265137
2     2020-03-05  5.710000038146973
3     2020-03-04  5.710000038146973
4     2020-03-03  5.639999866485596
...          ...                ...
1238  2015-03-16  7.265110015869141
1239  2015-03-13  7.199659824371338
1240  2015-03-12  7.237060070037842
1241  2015-03-11  7.349259853363037
1242  2015-03-10  7.386660099029541

[1243 rows x 2 columns]

In [5]:
# 1) You are required  to write code that will crawl the WWW (your familiar domain) of a particular website and collect data from social media or from report or news and so on and to produce dataset.
## Scrape KLCI Data
page = requests.get("https://finance.yahoo.com/quote/%5EKLSE%3FP%3D%5EKLSE/history?period1=1425945600&period2=1583798400&interval=1d&filter=history&frequency=1d")
page.status_code

from bs4 import BeautifulSoup
soup = BeautifulSoup(page.content, 'html.parser')
#print(soup.prettify())


listScript = soup.find_all("script")
for script in listScript:
    txtScript = script.string
    if type(txtScript) is bs4.element.NavigableString and txtScript.find('HistoricalPriceStore') != -1:
        KLCI = pd.DataFrame(columns=['date','close'])
        txtInfo = txtScript[txtScript.find('HistoricalPriceStore'):txtScript.find('}],"isPending":false,"firstTradeDate":')]
        txtInfo = "{\"" + txtInfo + "}]}}"
        objJson = json.loads(txtInfo)
        for price in objJson['HistoricalPriceStore']['prices']:
            txtDate = ""
            txtClose = ""
            for attr,val in price.items():
                if attr == "date" and val != None:
                    txtDate = datetime.datetime.fromtimestamp(val).strftime('%Y-%m-%d')
                if attr == "close" and val != None:
                    txtClose = str(val)
            if txtDate != "" and txtClose != "":
                KLCI = KLCI.append({"date":txtDate, "close":txtClose}, ignore_index=True)
        print(KLCI)
KLCI.to_csv(r'C:/Users/L-ven Lew/Desktop/UM/Semester 4 UM/WQD 7005 Data Mining/Final Exam/Final Exam Question 1/KLCI3.csv',index = False)
KLCI

            date               close
0     2020-03-09  1424.1600341796875
1     2020-03-06  1483.0999755859375
2     2020-03-05   1491.030029296875
3     2020-03-04   1489.949951171875
4     2020-03-03  1478.6400146484375
...          ...                 ...
1221  2015-03-16     1780.5400390625
1222  2015-03-13             1781.75
1223  2015-03-12  1786.8699951171875
1224  2015-03-11  1778.1600341796875
1225  2015-03-10    1789.72998046875

[1226 rows x 2 columns]

            date               close
0     2020-03-09  1424.1600341796875
1     2020-03-06  1483.0999755859375
2     2020-03-05   1491.030029296875
3     2020-03-04   1489.949951171875
4     2020-03-03  1478.6400146484375
...          ...                 ...
1221  2015-03-16     1780.5400390625
1222  2015-03-13             1781.75
1223  2015-03-12  1786.8699951171875
1224  2015-03-11  1778.1600341796875
1225  2015-03-10    1789.72998046875

[1226 rows x 2 columns]

In [6]:
import requests
import bs4
import json
import datetime
import pandas as pd
page = requests.get("https://finance.yahoo.com/quote/%5EDJI/history?period1=1425945600&period2=1583798400&interval=1d&filter=history&frequency=1d")

from bs4 import BeautifulSoup
soup = BeautifulSoup(page.content, 'html.parser')
#print(soup.prettify())

listScript = soup.find_all("script")
for script in listScript:
    txtScript = script.string
    if type(txtScript) is bs4.element.NavigableString and txtScript.find('HistoricalPriceStore') != -1:
        DJI = pd.DataFrame(columns=['date','close'])
        txtInfo = txtScript[txtScript.find('HistoricalPriceStore'):txtScript.find('}],"isPending":false,"firstTradeDate":')]
        txtInfo = "{\"" + txtInfo + "}]}}"
        objJson = json.loads(txtInfo)
        for price in objJson['HistoricalPriceStore']['prices']:
            txtDate = ""
            txtClose = ""
            for attr,val in price.items():
                if attr == "date" and val != None:
                    txtDate = datetime.datetime.fromtimestamp(val).strftime('%Y-%m-%d')
                if attr == "close" and val != None:
                    txtClose = str(val)
            if txtDate != "" and txtClose != "":
                DJI = DJI.append({"date":txtDate, "close":txtClose}, ignore_index=True)
        print(DJI)
        
DJI.to_csv(r"C:/Users/L-ven Lew/Desktop/UM/Semester 4 UM/WQD 7005 Data Mining/Final Exam/Final Exam Question 1/DJI.csv",index = False)

            date            close
0     2020-03-09   23851.01953125
1     2020-03-06  25864.779296875
2     2020-03-05  26121.279296875
3     2020-03-04     27090.859375
4     2020-03-03   25917.41015625
...          ...              ...
1254  2015-03-16  17977.419921875
1255  2015-03-13  17749.310546875
1256  2015-03-12  17895.220703125
1257  2015-03-11     17635.390625
1258  2015-03-10  17662.939453125

[1259 rows x 2 columns]

In [43]:
import requests
import bs4
import json
import datetime
import pandas as pd
page = requests.get("https://finance.yahoo.com/quote/%5EGSPC/history?period1=1425945600&period2=1583798400&interval=1d&filter=history&frequency=1d")
from bs4 import BeautifulSoup
soup = BeautifulSoup(page.content, 'html.parser')
#print(soup.prettify())

listScript = soup.find_all("script")
for script in listScript:
    txtScript = script.string
    if type(txtScript) is bs4.element.NavigableString and txtScript.find('HistoricalPriceStore') != -1:
        SNP = pd.DataFrame(columns=['date','close'])
        txtInfo = txtScript[txtScript.find('HistoricalPriceStore'):txtScript.find('}],"isPending":false,"firstTradeDate":')]
        txtInfo = "{\"" + txtInfo + "}]}}"
        objJson = json.loads(txtInfo)
        for price in objJson['HistoricalPriceStore']['prices']:
            txtDate = ""
            txtClose = ""
            for attr,val in price.items():
                if attr == "date" and val != None:
                    txtDate = datetime.datetime.fromtimestamp(val).strftime('%Y-%m-%d')
                if attr == "close" and val != None:
                    txtClose = str(val)
            if txtDate != "" and txtClose != "":
                SNP = SNP.append({"date":txtDate, "close":txtClose}, ignore_index=True)
        print(SNP)
        
SNP.to_csv(r"C:/Users/L-ven Lew/Desktop/UM/Semester 4 UM/WQD 7005 Data Mining/Final Exam/Final Exam Question 1/SNP.csv",index = False)
SNP

            date               close
0     2020-03-09    2746.56005859375
1     2020-03-06     2972.3701171875
2     2020-03-05    3023.93994140625
3     2020-03-04     3130.1201171875
4     2020-03-03     3003.3701171875
...          ...                 ...
1254  2015-03-16    2081.18994140625
1255  2015-03-13    2053.39990234375
1256  2015-03-12   2065.949951171875
1257  2015-03-11   2040.239990234375
1258  2015-03-10  2044.1600341796875

[1259 rows x 2 columns]

            date               close
0     2020-03-09    2746.56005859375
1     2020-03-06     2972.3701171875
2     2020-03-05    3023.93994140625
3     2020-03-04     3130.1201171875
4     2020-03-03     3003.3701171875
...          ...                 ...
1254  2015-03-16    2081.18994140625
1255  2015-03-13    2053.39990234375
1256  2015-03-12   2065.949951171875
1257  2015-03-11   2040.239990234375
1258  2015-03-10  2044.1600341796875

[1259 rows x 2 columns]

In [8]:
MBB['date'] = pd.to_datetime(MBB.date)
CIMB['date'] = pd.to_datetime(CIMB.date)
RHB['date'] = pd.to_datetime(RHB.date)
KLCI['date'] = pd.to_datetime(KLCI.date)
DJI['date'] = pd.to_datetime(DJI.date)
SNP['date'] = pd.to_datetime(SNP.date)

In [9]:
MBB['Type_of_Index'] = 'Malaysia Stock'
CIMB['Type_of_Index'] = 'Malaysia Stock'
RHB['Type_of_Index'] = 'Malaysia Stock'
KLCI['Type_of_Index'] = 'Malaysia Index'
DJI['Type_of_Index'] = 'US Index'
SNP['Type_of_Index'] = 'US Index'

In [10]:
MBB['Sector'] = 'Financial'
CIMB['Sector'] = 'Financial'
RHB['Sector'] = 'Financial'
KLCI['Sector'] = 'Top 30 Malaysia stock by Market Cap'
DJI['Sector'] = 'Top 30 US stock by Market Cap'
SNP['Sector'] = 'Top 500 US stock by Market Cap'

In [11]:
MBB['Market board'] = 'Main Board'
CIMB['Market board'] = 'Main Board'
RHB['Market board'] = 'Main Board'
KLCI['Market board'] = 'Kuala Lumpur Composite Index'
DJI['Market board'] = 'US Stock Excahnge'
SNP['Market board'] = 'US Stock Excahnge'

In [12]:
MBB['close'] = MBB['close'].astype(float)
CIMB['close'] = CIMB['close'].astype(float)
RHB['close'] = RHB['close'].astype(float)
KLCI['close']= KLCI['close'].astype(float)
DJI['close'] = DJI['close'].astype(float)
SNP['close'] = SNP['close'].astype(float)

In [13]:
MBB['Month_Year'] = pd.to_datetime(MBB['date']).dt.to_period('M')
CIMB['Month_Year'] = pd.to_datetime(CIMB['date']).dt.to_period('M')
RHB['Month_Year'] = pd.to_datetime(RHB['date']).dt.to_period('M')
KLCI['Month_Year'] = pd.to_datetime(KLCI['date']).dt.to_period('M')
DJI['Month_Year'] = pd.to_datetime(DJI['date']).dt.to_period('M')
SNP['Month_Year'] = pd.to_datetime(SNP['date']).dt.to_period('M')

In [14]:
MBB['Name of Stock/ Index'] = 'MBB'
CIMB['Name of Stock/ Index'] = 'CIMB'
RHB['Name of Stock/ Index'] = 'RHB'
KLCI['Name of Stock/ Index'] = 'KLCI'
DJI['Name of Stock/ Index'] = 'DJI'
SNP['Name of Stock/ Index'] = 'SNP'

In [15]:
MBB['Monthly_Average'] = MBB['close'].groupby(MBB['Month_Year']).transform('mean')
CIMB['Monthly_Average'] = CIMB['close'].groupby(CIMB['Month_Year']).transform('mean')
RHB['Monthly_Average'] = RHB['close'].groupby(RHB['Month_Year']).transform('mean')
KLCI['Monthly_Average'] = KLCI['close'].groupby(KLCI['Month_Year']).transform('mean')
DJI['Monthly_Average'] = DJI['close'].groupby(DJI['Month_Year']).transform('mean')
SNP['Monthly_Average'] = SNP['close'].groupby(SNP['Month_Year']).transform('mean')

In [16]:
MBB.info()
CIMB.info()
RHB.info()
KLCI.info()
DJI.info()
SNP.info()

MBB.head()
CIMB.head()
RHB.head()
KLCI.head()
DJI.head()
SNP.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1242 entries, 0 to 1241
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   date                  1242 non-null   datetime64[ns]
 1   close                 1242 non-null   float64
 2   Type_of_Index         1242 non-null   object
 3   Sector                1242 non-null   object
 4   Market board          1242 non-null   object
 5   Month_Year            1242 non-null   period[M]
 6   Name of Stock/ Index  1242 non-null   object
 7   Monthly_Average       1242 non-null   float64
dtypes: datetime64[ns](1), float64(2), object(4), period[M](1)
memory usage: 77.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1243 entries, 0 to 1242
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   date                  1243 non-null   datetime64[ns]
 1   close                 1243 non-null   float64
 2   Type_of_Index         1243 non-null   object
 3   Sector                1243 non-null   object
 4   Market board          1243 non-null   object
 5   Month_Year            1243 non-null   period[M]
 6   Name of Stock/ Index  1243 non-null   object
 7   Monthly_Average       1243 non-null   float64
dtypes: datetime64[ns](1), float64(2), object(4), period[M](1)
memory usage: 77.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1243 entries, 0 to 1242
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   date                  1243 non-null   datetime64[ns]
 1   close                 1243 non-null   float64
 2   Type_of_Index         1243 non-null   object
 3   Sector                1243 non-null   object
 4   Market board          1243 non-null   object
 5   Month_Year            1243 non-null   period[M]
 6   Name of Stock/ Index  1243 non-null   object
 7   Monthly_Average       1243 non-null   float64
dtypes: datetime64[ns](1), float64(2), object(4), period[M](1)
memory usage: 77.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1226 entries, 0 to 1225
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   date                  1226 non-null   datetime64[ns]
 1   close                 1226 non-null   float64
 2   Type_of_Index         1226 non-null   object
 3   Sector                1226 non-null   object
 4   Market board          1226 non-null   object
 5   Month_Year            1226 non-null   period[M]
 6   Name of Stock/ Index  1226 non-null   object
 7   Monthly_Average       1226 non-null   float64
dtypes: datetime64[ns](1), float64(2), object(4), period[M](1)
memory usage: 76.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   date                  1259 non-null   datetime64[ns]
 1   close                 1259 non-null   float64
 2   Type_of_Index         1259 non-null   object
 3   Sector                1259 non-null   object
 4   Market board          1259 non-null   object
 5   Month_Year            1259 non-null   period[M]
 6   Name of Stock/ Index  1259 non-null   object
 7   Monthly_Average       1259 non-null   float64
dtypes: datetime64[ns](1), float64(2), object(4), period[M](1)
memory usage: 78.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   date                  1259 non-null   datetime64[ns]
 1   close                 1259 non-null   float64
 2   Type_of_Index         1259 non-null   object
 3   Sector                1259 non-null   object
 4   Market board          1259 non-null   object
 5   Month_Year            1259 non-null   period[M]
 6   Name of Stock/ Index  1259 non-null   object
 7   Monthly_Average       1259 non-null   float64
dtypes: datetime64[ns](1), float64(2), object(4), period[M](1)
memory usage: 78.8+ KB

,date,close,Type_of_Index,Sector,Market board,Month_Year,Name of Stock/ Index,Monthly_Average
0,2020-03-09,2746.560059,US Index,Top 500 US stock by Market Cap,US Stock Excahnge,2020-03,SNP,2994.431722
1,2020-03-06,2972.370117,US Index,Top 500 US stock by Market Cap,US Stock Excahnge,2020-03,SNP,2994.431722
2,2020-03-05,3023.939941,US Index,Top 500 US stock by Market Cap,US Stock Excahnge,2020-03,SNP,2994.431722
3,2020-03-04,3130.120117,US Index,Top 500 US stock by Market Cap,US Stock Excahnge,2020-03,SNP,2994.431722
4,2020-03-03,3003.370117,US Index,Top 500 US stock by Market Cap,US Stock Excahnge,2020-03,SNP,2994.431722

In [17]:
MBB['Country'] = 'MY'
CIMB['Country'] = 'MY'
RHB['Country'] = 'MY'
KLCI['Country']= 'MY'
DJI['Country'] = 'US'
SNP['Country'] = 'US'

MBB['Index_Type'] = 'Stock'
CIMB['Index_Type'] = 'Stock'
RHB['Index_Type'] = 'Stock'
KLCI['Index_Type']= 'Stock'
DJI['Index_Type'] = 'Index'
SNP['Index_Type'] = 'index'

In [18]:
DF = pd.concat([MBB, CIMB, RHB, KLCI, DJI, SNP], ignore_index=True)
DF.rename(columns={'date':'Trading_Date',
                          'close':'Closing_Index/Price'},
                 inplace=True)

print(DF)
DF.isnull().sum()

     Trading_Date  Closing_Index/Price   Type_of_Index  \
0      2020-03-09             8.240000  Malaysia Stock
1      2020-03-06             8.500000  Malaysia Stock
2      2020-03-05             8.530000  Malaysia Stock
3      2020-03-04             8.470000  Malaysia Stock
4      2020-03-03             8.410000  Malaysia Stock
...           ...                  ...             ...
7467   2015-03-16          2081.189941        US Index
7468   2015-03-13          2053.399902        US Index
7469   2015-03-12          2065.949951        US Index
7470   2015-03-11          2040.239990        US Index
7471   2015-03-10          2044.160034        US Index

                              Sector       Market board Month_Year  \
0                          Financial         Main Board    2020-03
1                          Financial         Main Board    2020-03
2                          Financial         Main Board    2020-03
3                          Financial         Main Board    2020-03
4                          Financial         Main Board    2020-03
...                              ...                ...        ...
7467  Top 500 US stock by Market Cap  US Stock Excahnge    2015-03
7468  Top 500 US stock by Market Cap  US Stock Excahnge    2015-03
7469  Top 500 US stock by Market Cap  US Stock Excahnge    2015-03
7470  Top 500 US stock by Market Cap  US Stock Excahnge    2015-03
7471  Top 500 US stock by Market Cap  US Stock Excahnge    2015-03

     Name of Stock/ Index  Monthly_Average Country Index_Type
0                     MBB         8.423333      MY      Stock
1                     MBB         8.423333      MY      Stock
2                     MBB         8.423333      MY      Stock
3                     MBB         8.423333      MY      Stock
4                     MBB         8.423333      MY      Stock
...                   ...              ...     ...        ...
7467                  SNP      2074.022484      US      index
7468                  SNP      2074.022484      US      index
7469                  SNP      2074.022484      US      index
7470                  SNP      2074.022484      US      index
7471                  SNP      2074.022484      US      index

[7472 rows x 10 columns]

Trading_Date            0
Closing_Index/Price     0
Type_of_Index           0
Sector                  0
Market board            0
Month_Year              0
Name of Stock/ Index    0
Monthly_Average         0
Country                 0
Index_Type              0
dtype: int64

In [19]:
print(DF)

     Trading_Date  Closing_Index/Price   Type_of_Index  \
0      2020-03-09             8.240000  Malaysia Stock
1      2020-03-06             8.500000  Malaysia Stock
2      2020-03-05             8.530000  Malaysia Stock
3      2020-03-04             8.470000  Malaysia Stock
4      2020-03-03             8.410000  Malaysia Stock
...           ...                  ...             ...
7467   2015-03-16          2081.189941        US Index
7468   2015-03-13          2053.399902        US Index
7469   2015-03-12          2065.949951        US Index
7470   2015-03-11          2040.239990        US Index
7471   2015-03-10          2044.160034        US Index

                              Sector       Market board Month_Year  \
0                          Financial         Main Board    2020-03
1                          Financial         Main Board    2020-03
2                          Financial         Main Board    2020-03
3                          Financial         Main Board    2020-03
4                          Financial         Main Board    2020-03
...                              ...                ...        ...
7467  Top 500 US stock by Market Cap  US Stock Excahnge    2015-03
7468  Top 500 US stock by Market Cap  US Stock Excahnge    2015-03
7469  Top 500 US stock by Market Cap  US Stock Excahnge    2015-03
7470  Top 500 US stock by Market Cap  US Stock Excahnge    2015-03
7471  Top 500 US stock by Market Cap  US Stock Excahnge    2015-03

     Name of Stock/ Index  Monthly_Average Country Index_Type
0                     MBB         8.423333      MY      Stock
1                     MBB         8.423333      MY      Stock
2                     MBB         8.423333      MY      Stock
3                     MBB         8.423333      MY      Stock
4                     MBB         8.423333      MY      Stock
...                   ...              ...     ...        ...
7467                  SNP      2074.022484      US      index
7468                  SNP      2074.022484      US      index
7469                  SNP      2074.022484      US      index
7470                  SNP      2074.022484      US      index
7471                  SNP      2074.022484      US      index

[7472 rows x 10 columns]

In [20]:
# SELECT Index.Trading_ID, Type_of_Index, Country, Name of stock/ index
#    from Index_key.Index
#    join Name of stock/ index
#    on Name_of_stock/_index_key.Trading_ID = Index.Trading_ID limit 3;


DF[['Trading_Date', 'Type_of_Index', 'Country','Name of Stock/ Index','Sector','Market board']].head(3)

,Trading_Date,Type_of_Index,Country,Name of Stock/ Index,Sector,Market board
0,2020-03-09,Malaysia Stock,MY,MBB,Financial,Main Board
1,2020-03-06,Malaysia Stock,MY,MBB,Financial,Main Board
2,2020-03-05,Malaysia Stock,MY,MBB,Financial,Main Board

In [21]:
# SELECT index.Trading_ID, Type_of_Index, Country
#    from Index_key.index
#    join Name of Stock/ Index where Market board = "Main Board"
#    on Name_of_stock/_index_key.Trading_ID = index.Trading_ID limit 3;

DF[DF['Market board']== 'Main Board']

,Trading_Date,Closing_Index/Price,Type_of_Index,Sector,Market board,Month_Year,Name of Stock/ Index,Monthly_Average,Country,Index_Type
0,2020-03-09,8.24000,Malaysia Stock,Financial,Main Board,2020-03,MBB,8.423333,MY,Stock
1,2020-03-06,8.50000,Malaysia Stock,Financial,Main Board,2020-03,MBB,8.423333,MY,Stock
2,2020-03-05,8.53000,Malaysia Stock,Financial,Main Board,2020-03,MBB,8.423333,MY,Stock
3,2020-03-04,8.47000,Malaysia Stock,Financial,Main Board,2020-03,MBB,8.423333,MY,Stock
4,2020-03-03,8.41000,Malaysia Stock,Financial,Main Board,2020-03,MBB,8.423333,MY,Stock
...,...,...,...,...,...,...,...,...,...,...
3723,2015-03-16,7.26511,Malaysia Stock,Financial,Main Board,2015-03,RHB,7.367963,MY,Stock
3724,2015-03-13,7.19966,Malaysia Stock,Financial,Main Board,2015-03,RHB,7.367963,MY,Stock
3725,2015-03-12,7.23706,Malaysia Stock,Financial,Main Board,2015-03,RHB,7.367963,MY,Stock
3726,2015-03-11,7.34926,Malaysia Stock,Financial,Main Board,2015-03,RHB,7.367963,MY,Stock
3727,2015-03-10,7.38666,Malaysia Stock,Financial,Main Board,2015-03,RHB,7.367963,MY,Stock

In [22]:
# for i in range(1, len(DF)):
#    DF.loc[i, 'Change'] = DF.loc[i-1, 'Closing_Index/Price'] - DF.loc[i, 'Closing_Index/Price']
# print(DF)

In [23]:
MBB1 = MBB.iloc[:, 0:2]
CIMB1= CIMB.iloc[:, 0:2]
RHB1 = RHB.iloc[:, 0:2]
KLCI1 = KLCI.iloc[:, 0:2]
DJI1 = DJI.iloc[:, 0:2]
SNP1 = SNP.iloc[:, 0:2]

for i in range(1, len(MBB1)):
    MBB1.loc[i, 'Change'] = MBB1.loc[i-1, 'close'] - MBB1.loc[i, 'close']
print(MBB1)

for i in range(1, len(CIMB1)):
    CIMB1.loc[i, 'Change'] = CIMB1.loc[i-1, 'close'] - CIMB1.loc[i, 'close']
print(CIMB1)

for i in range(1, len(RHB1)):
    RHB1.loc[i, 'Change'] = RHB1.loc[i-1, 'close'] - RHB1.loc[i, 'close']
print(CIMB1)

for i in range(1, len(KLCI1)):
    KLCI1.loc[i, 'Change'] = KLCI1.loc[i-1, 'close'] - KLCI1.loc[i, 'close']
print(KLCI1)

for i in range(1, len(DJI1)):
    DJI1.loc[i, 'Change'] = DJI1.loc[i-1, 'close'] - DJI1.loc[i, 'close']
print(DJI1)

for i in range(1, len(SNP1)):
    SNP1.loc[i, 'Change'] = SNP1.loc[i-1, 'close'] - SNP1.loc[i, 'close']
print(SNP1)

           date  close    Change
0    2020-03-09   8.24       NaN
1    2020-03-06   8.50 -0.260000
2    2020-03-05   8.53 -0.030000
3    2020-03-04   8.47  0.059999
4    2020-03-03   8.41  0.060000
...         ...    ...       ...
1237 2015-03-16   9.09  0.070000
1238 2015-03-13   9.10 -0.010000
1239 2015-03-12   9.12 -0.020000
1240 2015-03-11   9.09  0.030000
1241 2015-03-10   9.23 -0.139999

[1242 rows x 3 columns]
           date  close  Change
0    2020-03-09   4.20     NaN
1    2020-03-06   4.44   -0.24
2    2020-03-05   4.50   -0.06
3    2020-03-04   4.54   -0.04
4    2020-03-03   4.50    0.04
...         ...    ...     ...
1238 2015-03-16   5.91    0.05
1239 2015-03-13   5.92   -0.01
1240 2015-03-12   5.85    0.07
1241 2015-03-11   5.80    0.05
1242 2015-03-10   5.95   -0.15

[1243 rows x 3 columns]
           date  close  Change
0    2020-03-09   4.20     NaN
1    2020-03-06   4.44   -0.24
2    2020-03-05   4.50   -0.06
3    2020-03-04   4.54   -0.04
4    2020-03-03   4.50    0.04
...         ...    ...     ...
1238 2015-03-16   5.91    0.05
1239 2015-03-13   5.92   -0.01
1240 2015-03-12   5.85    0.07
1241 2015-03-11   5.80    0.05
1242 2015-03-10   5.95   -0.15

[1243 rows x 3 columns]
           date        close     Change
0    2020-03-09  1424.160034        NaN
1    2020-03-06  1483.099976 -58.939941
2    2020-03-05  1491.030029  -7.930054
3    2020-03-04  1489.949951   1.080078
4    2020-03-03  1478.640015  11.309937
...         ...          ...        ...
1221 2015-03-16  1780.540039   7.329956
1222 2015-03-13  1781.750000  -1.209961
1223 2015-03-12  1786.869995  -5.119995
1224 2015-03-11  1778.160034   8.709961
1225 2015-03-10  1789.729980 -11.569946

[1226 rows x 3 columns]
           date         close       Change
0    2020-03-09  23851.019531          NaN
1    2020-03-06  25864.779297 -2013.759766
2    2020-03-05  26121.279297  -256.500000
3    2020-03-04  27090.859375  -969.580078
4    2020-03-03  25917.410156  1173.449219
...         ...           ...          ...
1254 2015-03-16  17977.419922  -128.339844
1255 2015-03-13  17749.310547   228.109375
1256 2015-03-12  17895.220703  -145.910156
1257 2015-03-11  17635.390625   259.830078
1258 2015-03-10  17662.939453   -27.548828

[1259 rows x 3 columns]
           date        close      Change
0    2020-03-09  2746.560059         NaN
1    2020-03-06  2972.370117 -225.810059
2    2020-03-05  3023.939941  -51.569824
3    2020-03-04  3130.120117 -106.180176
4    2020-03-03  3003.370117  126.750000
...         ...          ...         ...
1254 2015-03-16  2081.189941   -6.909912
1255 2015-03-13  2053.399902   27.790039
1256 2015-03-12  2065.949951  -12.550049
1257 2015-03-11  2040.239990   25.709961
1258 2015-03-10  2044.160034   -3.920044

[1259 rows x 3 columns]

In [24]:
def f(row):
    if row['Change'] > 0:
        val = 'Rise'
    elif row['Change'] < 0:
        val = 'Drop'
    else:
        val = 'No Change'
    return val

MBB1['Movement'] = MBB1.apply(f, axis=1)
CIMB1['Movement'] = CIMB1.apply(f, axis=1)
RHB1['Movement'] = RHB1.apply(f, axis=1)
KLCI1['Movement'] = KLCI1.apply(f, axis=1)
DJI1['Movement'] = DJI1.apply(f, axis=1)
SNP1['Movement'] = SNP1.apply(f, axis=1)

# MBB1['MBB_Movement'] = MBB1.apply(f, axis=1)
# CIMB1['CIMB1_Movement'] = CIMB1.apply(f, axis=1)
# RHB1['RHB1_Movement'] = RHB1.apply(f, axis=1)
# KLCI1['KLCI1_Movement'] = KLCI1.apply(f, axis=1)
# DJI1['DJI1_Movement'] = DJI1.apply(f, axis=1)
# SNP1['SNP1_Movement'] = SNP1.apply(f, axis=1

In [25]:
MBB1.rename(columns = {'Movement': 'MBB_Movement'}, inplace = True) 
CIMB1.rename(columns = {'Movement': 'CIMB1_Movement'}, inplace = True) 
RHB1.rename(columns = {'Movement': 'RHB1_Movement'}, inplace = True) 
KLCI1.rename(columns = {'Movement': 'KLCI1_Movement'}, inplace = True) 
DJI1.rename(columns = {'Movement': 'DJI1_Movement'}, inplace = True) 
SNP1.rename(columns = {'Movement': 'SNP1_Movement'}, inplace = True)

In [26]:
print(MBB1)
print(CIMB1)
print(RHB1)
print(KLCI1)
print(DJI1)
print(SNP1)

           date  close    Change MBB_Movement
0    2020-03-09   8.24       NaN    No Change
1    2020-03-06   8.50 -0.260000         Drop
2    2020-03-05   8.53 -0.030000         Drop
3    2020-03-04   8.47  0.059999         Rise
4    2020-03-03   8.41  0.060000         Rise
...         ...    ...       ...          ...
1237 2015-03-16   9.09  0.070000         Rise
1238 2015-03-13   9.10 -0.010000         Drop
1239 2015-03-12   9.12 -0.020000         Drop
1240 2015-03-11   9.09  0.030000         Rise
1241 2015-03-10   9.23 -0.139999         Drop

[1242 rows x 4 columns]
           date  close  Change CIMB1_Movement
0    2020-03-09   4.20     NaN      No Change
1    2020-03-06   4.44   -0.24           Drop
2    2020-03-05   4.50   -0.06           Drop
3    2020-03-04   4.54   -0.04           Drop
4    2020-03-03   4.50    0.04           Rise
...         ...    ...     ...            ...
1238 2015-03-16   5.91    0.05           Rise
1239 2015-03-13   5.92   -0.01           Drop
1240 2015-03-12   5.85    0.07           Rise
1241 2015-03-11   5.80    0.05           Rise
1242 2015-03-10   5.95   -0.15           Drop

[1243 rows x 4 columns]
           date    close   Change RHB1_Movement
0    2020-03-09  5.47000      NaN     No Change
1    2020-03-06  5.70000 -0.23000          Drop
2    2020-03-05  5.71000 -0.01000          Drop
3    2020-03-04  5.71000  0.00000     No Change
4    2020-03-03  5.64000  0.07000          Rise
...         ...      ...      ...           ...
1238 2015-03-16  7.26511  0.03740          Rise
1239 2015-03-13  7.19966  0.06545          Rise
1240 2015-03-12  7.23706 -0.03740          Drop
1241 2015-03-11  7.34926 -0.11220          Drop
1242 2015-03-10  7.38666 -0.03740          Drop

[1243 rows x 4 columns]
           date        close     Change KLCI1_Movement
0    2020-03-09  1424.160034        NaN      No Change
1    2020-03-06  1483.099976 -58.939941           Drop
2    2020-03-05  1491.030029  -7.930054           Drop
3    2020-03-04  1489.949951   1.080078           Rise
4    2020-03-03  1478.640015  11.309937           Rise
...         ...          ...        ...            ...
1221 2015-03-16  1780.540039   7.329956           Rise
1222 2015-03-13  1781.750000  -1.209961           Drop
1223 2015-03-12  1786.869995  -5.119995           Drop
1224 2015-03-11  1778.160034   8.709961           Rise
1225 2015-03-10  1789.729980 -11.569946           Drop

[1226 rows x 4 columns]
           date         close       Change DJI1_Movement
0    2020-03-09  23851.019531          NaN     No Change
1    2020-03-06  25864.779297 -2013.759766          Drop
2    2020-03-05  26121.279297  -256.500000          Drop
3    2020-03-04  27090.859375  -969.580078          Drop
4    2020-03-03  25917.410156  1173.449219          Rise
...         ...           ...          ...           ...
1254 2015-03-16  17977.419922  -128.339844          Drop
1255 2015-03-13  17749.310547   228.109375          Rise
1256 2015-03-12  17895.220703  -145.910156          Drop
1257 2015-03-11  17635.390625   259.830078          Rise
1258 2015-03-10  17662.939453   -27.548828          Drop

[1259 rows x 4 columns]
           date        close      Change SNP1_Movement
0    2020-03-09  2746.560059         NaN     No Change
1    2020-03-06  2972.370117 -225.810059          Drop
2    2020-03-05  3023.939941  -51.569824          Drop
3    2020-03-04  3130.120117 -106.180176          Drop
4    2020-03-03  3003.370117  126.750000          Rise
...         ...          ...         ...           ...
1254 2015-03-16  2081.189941   -6.909912          Drop
1255 2015-03-13  2053.399902   27.790039          Rise
1256 2015-03-12  2065.949951  -12.550049          Drop
1257 2015-03-11  2040.239990   25.709961          Rise
1258 2015-03-10  2044.160034   -3.920044          Drop

[1259 rows x 4 columns]

In [27]:
MBB2 = MBB1.drop(['close', 'Change'], axis=1)
CIMB2 = CIMB1.drop(['close', 'Change'], axis=1)
RHB2 = RHB1.drop(['close', 'Change'], axis=1)
KLCI2 = KLCI1.drop(['close', 'Change'], axis=1)
DJI2 = DJI1.drop(['close', 'Change'], axis=1)
SNP2 = SNP1.drop(['close', 'Change'], axis=1)

print(MBB2)
print(CIMB2)
print(RHB2)
print(KLCI2)
print(DJI2)
print(SNP2)

           date MBB_Movement
0    2020-03-09    No Change
1    2020-03-06         Drop
2    2020-03-05         Drop
3    2020-03-04         Rise
4    2020-03-03         Rise
...         ...          ...
1237 2015-03-16         Rise
1238 2015-03-13         Drop
1239 2015-03-12         Drop
1240 2015-03-11         Rise
1241 2015-03-10         Drop

[1242 rows x 2 columns]
           date CIMB1_Movement
0    2020-03-09      No Change
1    2020-03-06           Drop
2    2020-03-05           Drop
3    2020-03-04           Drop
4    2020-03-03           Rise
...         ...            ...
1238 2015-03-16           Rise
1239 2015-03-13           Drop
1240 2015-03-12           Rise
1241 2015-03-11           Rise
1242 2015-03-10           Drop

[1243 rows x 2 columns]
           date RHB1_Movement
0    2020-03-09     No Change
1    2020-03-06          Drop
2    2020-03-05          Drop
3    2020-03-04     No Change
4    2020-03-03          Rise
...         ...           ...
1238 2015-03-16          Rise
1239 2015-03-13          Rise
1240 2015-03-12          Drop
1241 2015-03-11          Drop
1242 2015-03-10          Drop

[1243 rows x 2 columns]
           date KLCI1_Movement
0    2020-03-09      No Change
1    2020-03-06           Drop
2    2020-03-05           Drop
3    2020-03-04           Rise
4    2020-03-03           Rise
...         ...            ...
1221 2015-03-16           Rise
1222 2015-03-13           Drop
1223 2015-03-12           Drop
1224 2015-03-11           Rise
1225 2015-03-10           Drop

[1226 rows x 2 columns]
           date DJI1_Movement
0    2020-03-09     No Change
1    2020-03-06          Drop
2    2020-03-05          Drop
3    2020-03-04          Drop
4    2020-03-03          Rise
...         ...           ...
1254 2015-03-16          Drop
1255 2015-03-13          Rise
1256 2015-03-12          Drop
1257 2015-03-11          Rise
1258 2015-03-10          Drop

[1259 rows x 2 columns]
           date SNP1_Movement
0    2020-03-09     No Change
1    2020-03-06          Drop
2    2020-03-05          Drop
3    2020-03-04          Drop
4    2020-03-03          Rise
...         ...           ...
1254 2015-03-16          Drop
1255 2015-03-13          Rise
1256 2015-03-12          Drop
1257 2015-03-11          Rise
1258 2015-03-10          Drop

[1259 rows x 2 columns]

In [28]:
TD_Dataset = pd.merge(MBB2, CIMB2,  
                        how="left", on=["date"])

In [29]:
TD_Dataset1 = pd.merge(KLCI2, TD_Dataset,  
                        how="left", on=["date"])

In [30]:
TD_Dataset2 = pd.merge(TD_Dataset1, RHB2,  
                        how="left", on=["date"])

In [31]:
TD_Dataset3 = pd.merge(TD_Dataset2, DJI2,  
                        how="left", on=["date"])

In [32]:
TD_Dataset4 = pd.merge(TD_Dataset3, SNP2,  
                        how="left", on=["date"])
TD_Dataset4

,date,KLCI1_Movement,MBB_Movement,CIMB1_Movement,RHB1_Movement,DJI1_Movement,SNP1_Movement
0,2020-03-09,No Change,No Change,No Change,No Change,No Change,No Change
1,2020-03-06,Drop,Drop,Drop,Drop,Drop,Drop
2,2020-03-05,Drop,Drop,Drop,Drop,Drop,Drop
3,2020-03-04,Rise,Rise,Drop,No Change,Drop,Drop
4,2020-03-03,Rise,Rise,Rise,Rise,Rise,Rise
...,...,...,...,...,...,...,...
1221,2015-03-16,Rise,Rise,Rise,Rise,Drop,Drop
1222,2015-03-13,Drop,Drop,Drop,Rise,Rise,Rise
1223,2015-03-12,Drop,Drop,Rise,Drop,Drop,Drop
1224,2015-03-11,Rise,Rise,Rise,Drop,Rise,Rise
1225,2015-03-10,Drop,Drop,Drop,Drop,Drop,Drop

In [33]:
MergeD = pd.merge(KLCI1, DJI1,
                      how="left", on=["date"])

MergeD1 = pd.merge(MergeD,SNP1,
                      how="left", on=["date"])

MergeD2 = pd.merge(MergeD1,MBB2,
                      how="left", on=["date"])

MergeD3 = pd.merge(MergeD2, RHB2,
                      how="left", on=["date"])

Tree_Decision_Dataset = pd.merge(MergeD3, CIMB2,
                      how="left", on=["date"])

In [34]:
Tree_Decision_Dataset1 = Tree_Decision_Dataset.dropna(how='any',axis=0)
print(Tree_Decision_Dataset1.isnull().sum())
     
print(Tree_Decision_Dataset1)

date              0
close_x           0
Change_x          0
KLCI1_Movement    0
close_y           0
Change_y          0
DJI1_Movement     0
close             0
Change            0
SNP1_Movement     0
MBB_Movement      0
RHB1_Movement     0
CIMB1_Movement    0
dtype: int64
           date      close_x   Change_x KLCI1_Movement       close_y  \
1    2020-03-06  1483.099976 -58.939941           Drop  25864.779297
2    2020-03-05  1491.030029  -7.930054           Drop  26121.279297
3    2020-03-04  1489.949951   1.080078           Rise  27090.859375
4    2020-03-03  1478.640015  11.309937           Rise  25917.410156
5    2020-03-02  1466.939941  11.700073           Rise  26703.320312
...         ...          ...        ...            ...           ...
1221 2015-03-16  1780.540039   7.329956           Rise  17977.419922
1222 2015-03-13  1781.750000  -1.209961           Drop  17749.310547
1223 2015-03-12  1786.869995  -5.119995           Drop  17895.220703
1224 2015-03-11  1778.160034   8.709961           Rise  17635.390625
1225 2015-03-10  1789.729980 -11.569946           Drop  17662.939453

         Change_y DJI1_Movement        close      Change SNP1_Movement  \
1    -2013.759766          Drop  2972.370117 -225.810059          Drop
2     -256.500000          Drop  3023.939941  -51.569824          Drop
3     -969.580078          Drop  3130.120117 -106.180176          Drop
4     1173.449219          Rise  3003.370117  126.750000          Rise
5     -785.910156          Drop  3090.229980  -86.859863          Drop
...           ...           ...          ...         ...           ...
1221  -128.339844          Drop  2081.189941   -6.909912          Drop
1222   228.109375          Rise  2053.399902   27.790039          Rise
1223  -145.910156          Drop  2065.949951  -12.550049          Drop
1224   259.830078          Rise  2040.239990   25.709961          Rise
1225   -27.548828          Drop  2044.160034   -3.920044          Drop

     MBB_Movement RHB1_Movement CIMB1_Movement
1            Drop          Drop           Drop
2            Drop          Drop           Drop
3            Rise     No Change           Drop
4            Rise          Rise           Rise
5            Rise          Rise           Drop
...           ...           ...            ...
1221         Rise          Rise           Rise
1222         Drop          Rise           Drop
1223         Drop          Drop           Rise
1224         Rise          Drop           Rise
1225         Drop          Drop           Drop

[1192 rows x 13 columns]

In [35]:
# Load libraries
import pandas as pd
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn import tree
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics

In [36]:
## MayBank Stock price movement vs daily change of KLCI, DJI & SNP
# feature selection

# KLCI1_Movement vs MayBank
feature_cols = ['Change_x']
X = Tree_Decision_Dataset1[feature_cols] # Features
y = Tree_Decision_Dataset1.MBB_Movement # Target variable

In [37]:
## MayBank Stock price movement vs daily change of KLCI
# Split dataset into training set and test set
# 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [38]:
## MayBank Stock price movement vs daily change of KLCI
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [39]:
## MayBank Stock price movement vs daily change of KLCI
accuracy = metrics.accuracy_score(y_test,y_pred)
accuracy

0.5446927374301676

In [42]:
## MayBank Stock price movement vs daily change of KLCI
from matplotlib import pyplot as plt
fn=['Change']
cn=['Rise', 'Drop', 'No Change']
fig, axes = plt.subplots(nrows = 1,ncols = 1,figsize = (4,4), dpi=300)
tree.plot_tree(clf,
               feature_names = fn, 
               class_names=cn,
               filled = True);
fig.savefig('imagename1.png')
# tree.plot_tree(clf) # alternative

AttributeError: module 'matplotlib.cbook' has no attribute '_classproperty'

In [ ]:
# DJI1_Movement vs MayBank
feature_cols = ['Change_y']
X = Tree_Decision_Dataset1[feature_cols] # Features
y = Tree_Decision_Dataset1.MBB_Movement # Target variable

In [ ]:
## MayBank Stock price movement vs daily change of DJI
# Split dataset into training set and test set
# 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [ ]:
## MayBank Stock price movement vs daily change of DJI
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [ ]:
## MayBank Stock price movement vs daily change of DJI
accuracy = metrics.accuracy_score(y_test,y_pred)
accuracy

In [ ]:
## MayBank Stock price movement vs daily change of DJI
from matplotlib import pyplot as plt
fn=['Change']
cn=['Rise', 'Drop', 'No Change']
fig, axes = plt.subplots(nrows = 1,ncols = 1,figsize = (4,4), dpi=300)
tree.plot_tree(clf,
               feature_names = fn, 
               class_names=cn,
               filled = True);
fig.savefig('imagename2.png')
tree.plot_tree(clf) # alternative

In [ ]:
# SNP1_Movement vs MayBank
feature_cols = ['Change']
X = Tree_Decision_Dataset1[feature_cols] # Features
y = Tree_Decision_Dataset1.MBB_Movement # Target variable

In [ ]:
## MayBank Stock price movement vs daily change of SNP
# Split dataset into training set and test set
# 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [ ]:
## MayBank Stock price movement vs daily change of SNP
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [ ]:
## MayBank Stock price movement vs daily change of SNP
accuracy = metrics.accuracy_score(y_test,y_pred)
accuracy

In [ ]:
## MayBank Stock price movement vs daily change of SNP
from matplotlib import pyplot as plt
fn=['Change']
cn=['Rise', 'Drop', 'No Change']
fig, axes = plt.subplots(nrows = 1,ncols = 1,figsize = (4,4), dpi=300)
tree.plot_tree(clf,
               feature_names = fn, 
               class_names=cn,
               filled = True);
fig.savefig('imagename3.png')
tree.plot_tree(clf) # alternative

In [ ]:
## CIMB price movement vs daily change of KLCI, DJI & SNP
# feature selection

# KLCI1_Movement vs CIMB
feature_cols = ['Change_x']
X = Tree_Decision_Dataset1[feature_cols] # Features
y = Tree_Decision_Dataset1.CIMB1_Movement # Target variable

In [ ]:
## CIMB Stock price movement vs daily change of KLCI
# Split dataset into training set and test set
# 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [ ]:
## CIMB Stock price movement vs daily change of KLCI
# Split dataset into training set and test set
# 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [ ]:
## CIMB Stock price movement vs daily change of KLCI
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [ ]:
## CIMB Stock price movement vs daily change of KLCI
accuracy = metrics.accuracy_score(y_test,y_pred)
accuracy

In [ ]:
## CIMB Stock price movement vs daily change of KLCI
from matplotlib import pyplot as plt
fn=['Change_x']
cn=['Rise', 'Drop', 'No Change']
fig, axes = plt.subplots(nrows = 1,ncols = 1,figsize = (4,4), dpi=300)
tree.plot_tree(clf,
               feature_names = fn, 
               class_names=cn,
               filled = True);
fig.savefig('imagename4.png')

tree.plot_tree(clf) # alternative

In [ ]:
## CIMB price movement vs daily change of DJI 
# feature selection

# DJI vs CIMB
feature_cols = ['Change_y']
X = Tree_Decision_Dataset1[feature_cols] # Features
y = Tree_Decision_Dataset1.CIMB1_Movement # Target variable

In [ ]:
## CIMB Stock price movement vs daily change of DJI
# Split dataset into training set and test set
# 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [ ]:
## CIMB Stock price movement vs daily change of DJI
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [ ]:
## CIMB Stock price movement vs daily change of DJI
accuracy = metrics.accuracy_score(y_test,y_pred)
accuracy

In [ ]:
## CIMB Stock price movement vs daily change of DJI
from matplotlib import pyplot as plt
fn=['Change_y']
cn=['Rise', 'Drop', 'No Change']
fig, axes = plt.subplots(nrows = 1,ncols = 1,figsize = (4,4), dpi=300)
tree.plot_tree(clf,
               feature_names = fn, 
               class_names=cn,
               filled = True);
fig.savefig('imagename5.png')

tree.plot_tree(clf) # alternative

In [ ]:
## CIMB price movement vs daily change of SNP
# feature selection

# SNP vs CIMB
feature_cols = ['Change']
X = Tree_Decision_Dataset1[feature_cols] # Features
y = Tree_Decision_Dataset1.CIMB1_Movement # Target variable

In [ ]:
## CIMB Stock price movement vs daily change of SNP
# Split dataset into training set and test set
# 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [ ]:
## CIMB Stock price movement vs daily change of SNP
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [ ]:
## CIMB Stock price movement vs daily change of SNP
accuracy = metrics.accuracy_score(y_test,y_pred)
accuracy

In [ ]:
## CIMB Stock price movement vs daily change of SNP
from matplotlib import pyplot as plt
fn=['Change']
cn=['Rise', 'Drop', 'No Change']
fig, axes = plt.subplots(nrows = 1,ncols = 1,figsize = (4,4), dpi=300)
tree.plot_tree(clf,
               feature_names = fn, 
               class_names=cn,
               filled = True);
fig.savefig('imagename6.png')

tree.plot_tree(clf) # alternative

In [ ]:
## RHB price movement vs daily change of KLCI, DJI & SNP
# feature selection

# KLCI1_Movement vs  RHB 
feature_cols = ['Change_x']
X = Tree_Decision_Dataset1[feature_cols] # Features
y = Tree_Decision_Dataset1.RHB1_Movement # Target variable

In [ ]:
##  RHB  Stock price movement vs daily change of KLCI
# Split dataset into training set and test set
# 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [ ]:
##  RHB  Stock price movement vs daily change of KLCI
# Split dataset into training set and test set
# 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [ ]:
##  RHB  Stock price movement vs daily change of KLCI
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [ ]:
##  RHB  Stock price movement vs daily change of KLCI
accuracy = metrics.accuracy_score(y_test,y_pred)
accuracy

In [ ]:
##  RHB Stock price movement vs daily change of KLCI
from matplotlib import pyplot as plt
fn=['Change_x']
cn=['Rise', 'Drop', 'No Change']
fig, axes = plt.subplots(nrows = 1,ncols = 1,figsize = (4,4), dpi=300)
tree.plot_tree(clf,
               feature_names = fn, 
               class_names=cn,
               filled = True);
fig.savefig('imagename7.png')
# tree.plot_tree(clf) # alternative

In [ ]:
## RHB  price movement vs daily change of DJI 
# feature selection

# DJI vs CIMB
feature_cols = ['Change_y']
X = Tree_Decision_Dataset1[feature_cols] # Features
y = Tree_Decision_Dataset1.RHB1_Movement # Target variable

In [ ]:
##  RHB  Stock price movement vs daily change of DJI
# Split dataset into training set and test set
# 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [ ]:
## CIMB Stock price movement vs daily change of DJI
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [ ]:
##  RHB  Stock price movement vs daily change of DJI
accuracy = metrics.accuracy_score(y_test,y_pred)
accuracy

In [ ]:
##  RHB  Stock price movement vs daily change of DJI
from matplotlib import pyplot as plt
fn=['Change_y']
cn=['Rise', 'Drop', 'No Change']
fig, axes = plt.subplots(nrows = 1,ncols = 1,figsize = (4,4), dpi=300)
tree.plot_tree(clf,
               feature_names = fn, 
               class_names=cn,
               filled = True);
fig.savefig('imagename8.png')
tree.plot_tree(clf) # alternative

In [ ]:
##  RHB price movement vs daily change of SNP
# feature selection

# SNP vs RHB
feature_cols = ['Change']
X = Tree_Decision_Dataset1[feature_cols] # Features
y = Tree_Decision_Dataset1.RHB1_Movement # Target variable

In [ ]:
## RHB Stock price movement vs daily change of SNP
# Split dataset into training set and test set
# 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [ ]:
##  RHB  Stock price movement vs daily change of SNP
# Create Decision Tree classifer object
clf = DecisionTreeClassifier()

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [ ]:
## RHB Stock price movement vs daily change of SNP
accuracy = metrics.accuracy_score(y_test,y_pred)
accuracy

In [ ]:
##  RHB  Stock price movement vs daily change of SNP
from matplotlib import pyplot as plt
fn=['Change']
cn=['Rise', 'Drop', 'No Change']
fig, axes = plt.subplots(nrows = 1,ncols = 1,figsize = (4,4), dpi=300)
tree.plot_tree(clf,
               feature_names = fn, 
               class_names=cn,
               filled = True);
fig.savefig('imagename9.png')
tree.plot_tree(clf) # alternative

In [ ]:
TD_Dataset4

In [ ]:
TD_Dataset5 = TD_Dataset4.replace(to_replace={"KLCI1_Movement": {"No Change": "KLCI:No_Change", "Drop": "KLCI:Drop","Rise": "KLCI:Rise"}, 
                                "MBB_Movement": {"No Change": "MBB:No_Change", "Drop": "MBB:Drop","Rise": "MBB:Rise"}, 
                                "CIMB1_Movement": {"No Change": "CIMB:No_Change", "Drop": "CIMB:Drop","Rise": "CIMB:Rise"},
                                "RHB1_Movement": {"No Change": "RHB:No_Change", "Drop": "RHB:Drop","Rise": "RHB:Rise"},
                                "DJI1_Movement": {"No Change": "DJI:No_Change", "Drop": "DJI:Drop","Rise": "DJI:Rise"},
                                "SNP1_Movement": {"No Change": "SNP:No_Change", "Drop": "SNP:Drop","Rise": "SNP:Rise"}})

In [ ]:
print(TD_Dataset5)

In [ ]:
TD_Dataset5.isnull().sum()
TD_Dataset6 = TD_Dataset5.dropna(how='any',axis=0)
TD_Dataset6.isnull().sum()

In [ ]:
TD_Dataset6['date'] = TD_Dataset6['date'].astype('str') 
TD_Dataset6.info()

In [ ]:
KLCI = TD_Dataset6.loc[:,['date','KLCI1_Movement']]
MBB = TD_Dataset6.loc[:,['date','MBB_Movement']]
CIMB = TD_Dataset6.loc[:,['date','CIMB1_Movement']]
RHB = TD_Dataset6.loc[:,['date','RHB1_Movement']]
DJI = TD_Dataset6.loc[:,['date','DJI1_Movement']]
SNP = TD_Dataset6.loc[:,['date','SNP1_Movement']]

In [ ]:
KLCI.rename(columns={'date':'Trading_Date',
                          'KLCI1_Movement':'Movement'},inplace=True)
MBB.rename(columns={'date':'Trading_Date',
                          'MBB_Movement':'Movement'},inplace=True)
CIMB.rename(columns={'date':'Trading_Date',
                          'CIMB1_Movement':'Movement'},inplace=True)
RHB.rename(columns={'date':'Trading_Date',
                          'RHB1_Movement':'Movement'},inplace=True)
DJI.rename(columns={'date':'Trading_Date',
                          'DJI1_Movement':'Movement'},inplace=True)
SNP.rename(columns={'date':'Trading_Date',
                          'SNP1_Movement':'Movement'},inplace=True)

In [ ]:
DATASET_AM = pd.concat([MBB, CIMB, RHB, KLCI, DJI, SNP], ignore_index=True)
DATASET_AM.sort_values(by=['Trading_Date'], inplace=True)
DATASET_AM["Frequency"] = 1
DATASET_AM

In [ ]:
MyBasket= (DATASET_AM.groupby(['Trading_Date','Movement'])['Frequency'].sum()
           .unstack().reset_index().fillna(0).set_index('Trading_Date'))

def my_encode_units(x):
    if x <=0:
        return 0
    if x >=1:
        return 1

my_basket_sets = MyBasket.applymap(my_encode_units)
my_basket_sets

In [ ]:
# Training the Model
## Generating Frequent Itemsets
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
my_frequent_itemsets = apriori(my_basket_sets, min_support = 0.07, use_colnames = True)
my_frequent_itemsets

In [ ]:
my_rules = association_rules(my_frequent_itemsets, metric = 'lift', min_threshold=1)

In [ ]:
my_rules.head()

In [ ]:
my_basket_sets['DJI:Drop'].sum()
my_basket_sets['CIMB:Drop'].sum()

In [ ]:
my_rules[(my_rules['lift']>=3.6)&
        (my_rules['confidence']>=0.7)]

In [ ]:
DATASET_AM

In [ ]:
import pyfpgrowth
import networkx as nx
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
grouped_df = DATASET_AM.groupby(by = ['Trading_Date'])

transactions = []
for group, pdf in grouped_df:
    transactions.append(pdf['Movement'].values.tolist())

transactions

In [ ]:
patterns = pyfpgrowth.find_frequent_patterns(transactions,300 )
patterns

In [ ]:
rules = pyfpgrowth.generate_association_rules(patterns, 0.93)
rules

In [ ]:
my_rules[(my_rules['lift']>=3.5)&
        (my_rules['confidence']>=0.7)]

In [ ]:
SNP1['date'] =pd.to_datetime(SNP1.date)
SNP1.sort_values(by='date')

In [48]:
SNP_4 = SNP1.set_index(['date'])
SNP_4.sort_index(ascending = True)
indexedDataset = SNP_4.drop(['SNP1_Movement', 'Change'], axis=1).sort_index(ascending = True)
print(indexedDataset)

                  close
date
2015-03-10  2044.160034
2015-03-11  2040.239990
2015-03-12  2065.949951
2015-03-13  2053.399902
2015-03-16  2081.189941
...                 ...
2020-03-03  3003.370117
2020-03-04  3130.120117
2020-03-05  3023.939941
2020-03-06  2972.370117
2020-03-09  2746.560059

[1259 rows x 1 columns]

In [67]:
import numpy as np
import matplotlib.pyplot as plt

plt.xlabel('Trading Date')
plt.ylabel('SNP Index Movement')
plt.plot(indexedDataset)

AttributeError: 'Line2D' object has no attribute 'items'

In [ ]:
# Estimate the trend
indexedDataset_logScale= np.log(indexedDataset)
plt.plot(indexedDataset_logScale)

In [ ]:
# Estimate the trend based on moving average
movingAverage = indexedDataset_logScale.rolling(window=100).mean()
movingSTD = indexedDataset_logScale.rolling(window=100).std()
plt.plot(indexedDataset_logScale)
plt.plot(movingAverage, color ='red')
# Because the trend is moving with the time, we can conclude non-stationary

In [ ]:
datasetLogScaleMinusMovingAverage = indexedDataset_logScale - movingAverage
datasetLogScaleMinusMovingAverage.head(5)
print(plt.plot(datasetLogSclaeMinusMovingAverage, color ='red'))

# Remove the NaN value
datasetLogScaleMinusMovingAverage.dropna(inplace = True)
datasetLogScaleMinusMovingAverage.head(5)

In [ ]:
# use the function below to determine if the data is stationary 
def test_stationarity(timeseries):
    
    #Determing rolling statistics
    movingAverage = timeseries.rolling(window=100).mean()
    movingSTD = timeseries.rolling(window=100).std()

    #Plot rolling statistics:
    orig = plt.plot(timeseries, color='blue',label='Original')
    mean = plt.plot(movingAverage, color='red', label='Rolling Mean')
    std = plt.plot(movingSTD, color='black', label = 'Rolling Std')
    plt.legend(loc='best')
    plt.title('Rolling Mean & Standard Deviation')
    plt.show(block=False)
    
    #Perform Dickey-Fuller test:
    print ('Results of Dickey-Fuller Test:')
    dftest = adfuller(timeseries['close'], autolag='AIC')
    dfoutput = pd.Series(dftest[0:4], index=['Test Statistic','p-value','#Lags Used','Number of Observations Used'])
    for key,value in dftest[4].items():
        dfoutput['Critical Value (%s)'%key] = value
    print (dfoutput)

In [ ]:
test_stationarity(datasetLogSclaeMinusMovingAverage)
# P -value relatively less
# critical value almost equal, which tells dataset is stationary

In [ ]:
# Calcualte the weighted average of time series to see th trend that is present in a time-series
exponentialDecayWeightedAverage = indexedDataset_logScale.ewm(halflife = 100, min_periods =0, adjust = True).mean()
plt.plot(indexedDataset_logScale)
plt.plot(exponentialDecayWeightedAverage, color ='red')
# upward trend in respect with time

In [ ]:
datasetLogSclaeMinusExponentialDecayWeightedAverage = indexedDataset_logScale - exponentialDecayWeightedAverage
test_stationarity(datasetLogSclaeMinusExponentialDecayWeightedAverage)
# Remove the NaN value
datasetLogSclaeMinusExponentialDecayWeightedAverage.dropna(inplace = True)
datasetLogSclaeMinusExponentialDecayWeightedAverage.head(5)

In [ ]:
# shift the value into time-series for forecasting
datasetLogDiffShifting = indexedDataset_logScale - indexedDataset_logScale.shift()
plt.plot(datasetLogDiffShifting)

In [ ]:
datasetLogDiffShifting.dropna(inplace=True)
test_stationarity(datasetLogDiffShifting)
# null hypothesis is rejected, time-series is stationary

In [61]:
# component of time-series
from statsmodels.tsa.seasonal import seasonal_decompose
decomposition = seasonal_decompose(indexedDataset_logScale, freq=30) # decompose seasonal and segregate the 3 component


trend = decomposition.trend
seasonal = decomposition.seasonal
residual = decomposition.resid

plt.subplot(411)
plt.plot(indexedDataset_logScale, label ='Original')
plt.legend(loc ='Best')
plt.subplot(412)
plt.plot(trend, label ='Trend')
plt.legend(loc ='Best')
plt.subplot(413)
plt.plot(seasonal, label ='Seasonality')
plt.legend(loc ='Best')
plt.subplot(414)
plt.plot(residual, label = 'Residual')
plt.legend(loc='Best')
plt.tight_layout()

NameError: name 'indexedDataset_logScale' is not defined

In [ ]:
decomposedLogData = residual
decomposedLogData.dropna(inplace= True)
test_stationarity(decomposedLogData)

In [ ]:
# Plot ACF to calculate q value = Moving Average
# plot PFCA graph to calculate the value of P = Autoregression
from statsmodels.tsa.stattools import acf, pacf 
lag_acf =acf(datasetLogDiffShifting, nlags =20)
lag_pacf = pacf(datasetLogDiffShifting, nlags =20, method = 'ols') # ordinary least square

# plot ACF q value = Moving Average:
plt.subplot(121)
plt.plot(lag_acf)
plt.axhline(y=0, linestyle = '--', color ='gray')
plt.axhline(y=-1.96/np.sqrt(len(datasetLogDiffShifting)), linestyle = '--', color = 'gray')
plt.axhline(y=1.96/np.sqrt(len(datasetLogDiffShifting)), linestyle = '--', color = 'gray')
plt.title('Autocorrelation Function')

# plot PACF P = Autoregression:
plt.subplot(122)
plt.plot(lag_pacf)
plt.axhline(y=0, linestyle = '--', color ='gray')
plt.axhline(y=-1.96/np.sqrt(len(datasetLogDiffShifting)), linestyle = '--', color = 'gray')
plt.axhline(y=1.96/np.sqrt(len(datasetLogDiffShifting)), linestyle = '--', color = 'gray')
plt.title('Partial Autocorrection Function')

# to calcualte the P and Q value, refer to the value where the graph cut off
# AR (p): Autoregression. A model that uses the dependent relationship between an observation and some number of lagged observations. 
# Integrated (d). The use of differencing of raw observations 
# (d values e.g. subtracting an observation from an observation at the previous time step) in order to make the time series stationary.
# Moving Average (q). A model that uses the dependency between an observation and a residual error from a moving average model applied to lagged observations.
# Partial Autocorrelcation (P= value) = almost 1 
# Note that the PACF plot has a significant spike only at lag 1, 
# meaning that all the higher-order autocorrelations are effectively explained by the lag-1 autocorrelation.

In [ ]:
from statsmodels.tsa.arima_model import ARIMA
# AR Model
decomposition = seasonal_decompose(indexedDataset_logScale, freq=30)
model = ARIMA(indexedDataset_logScale, order =(2,1,2))
results_AR = model.fit(disp =-1)
plt.plot(datasetLogDiffShifting)
plt.plot(results_AR.fittedvalues, color = 'red')
plt.title('RSS: %.4f'% sum ((results_AR.fittedvalues-datasetLogDiffShifting['close'])**2))
print('Plotting AR model')

In [ ]:
# MA Model
model = ARIMA(indexedDataset_logScale, order =(0,1,2))
results_MA = model.fit(disp =-1)
plt.plot(datasetLogDiffShifting)
plt.plot(results_MA.fittedvalues, color = 'red')
plt.title('RSS: %.4f'% sum ((results_MA.fittedvalues-datasetLogDiffShifting['close'])**2))
print('Plotting MA model')

In [ ]:
model = ARIMA(indexedDataset_logScale, order =(2,1,0))
results_ARIMA = model.fit(disp =-1)
plt.plot(datasetLogDiffShifting)
plt.plot(results_ARIMA.fittedvalues, color = 'red')
plt.title('RSS: %.4f'% sum ((results_ARIMA.fittedvalues-datasetLogDiffShifting['close'])**2))
print('Plotting ARIMA model')

In [ ]:
results_ARIMA.plot_predict(1,2518)
# 1259+1259 = 2518